'use client';

import { Lightbulb, X } from 'lucide-react';
import type { FinancialInsight } from '@/lib/services/insights';
import { confidenceLabel, humanizeEnum, severityMeta } from '@/features/intelligence/lib/display';
import { Badge } from '@/shared/components/ui/badge';
import { Button } from '@/shared/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/shared/components/ui/sheet';
import { formatDate } from '@/shared/utils/format';

export function InsightDetailsDrawer({
  insight,
  open,
  onOpenChange,
  onDismiss,
}: {
  insight: FinancialInsight | null;
  open: boolean;
  onOpenChange: (o: boolean) => void;
  onDismiss?: (id: string) => void;
}) {
  const sev = insight ? severityMeta(insight.severity) : null;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-md">
        <SheetHeader>
          <SheetTitle>{insight?.riskType ? 'Risk details' : 'Insight details'}</SheetTitle>
          <SheetDescription>Generated by the Financial Intelligence engine.</SheetDescription>
        </SheetHeader>

        {insight && sev && (
          <div className="flex-1 space-y-4 overflow-y-auto p-5">
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant={sev.variant}>{sev.label}</Badge>
              {insight.category && <Badge variant="secondary">{insight.category}</Badge>}
              <Badge variant="outline">{humanizeEnum(insight.riskType ?? insight.insightType)}</Badge>
            </div>

            <div>
              <h3 className="text-base font-semibold text-foreground">{insight.title}</h3>
              <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{insight.description}</p>
            </div>

            {insight.actionSuggestion && (
              <div className="flex items-start gap-2 rounded-lg bg-primary/8 p-3 text-sm text-foreground">
                <Lightbulb className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden />
                <div>
                  <p className="font-medium">Suggested action</p>
                  <p className="text-muted-foreground">{insight.actionSuggestion}</p>
                </div>
              </div>
            )}

            <dl className="space-y-2 border-t border-border pt-4 text-sm">
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Confidence</dt>
                <dd className="font-medium text-foreground">{confidenceLabel(insight.confidence)}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Generated</dt>
                <dd className="font-medium text-foreground">{formatDate(insight.createdAt)}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">Expires</dt>
                <dd className="font-medium text-foreground">{formatDate(insight.expiresAt)}</dd>
              </div>
            </dl>
          </div>
        )}

        <SheetFooter>
          {insight && onDismiss && (
            <Button variant="outline" className="w-full" onClick={() => onDismiss(insight.id)}>
              <X />
              Dismiss
            </Button>
          )}
        </SheetFooter>
      </SheetContent>
    </Sheet>
  );
}
